version: 2.1

orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/visualtest-cypress/test

    steps:
      - checkout:
          path: ~/visualtest-cypress

#       Download and cache dependencies

#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run: npm install

      - run: npx cypress install

#      - run: sudo apt-get update
#
#      - run: sudo apt-get install libnss3

#      - run: sudo apt-get install -y libnss3


#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test


