name: browser-type-check
on: [push]
#on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        browser: [ 'chrome:beta', 'edge:beta' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Edge Beta
        if: ${{ startsWith(matrix.browser, 'edge') }}
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge-beta stable main" > /etc/apt/sources.list.d/microsoft-edge-beta.list'
          sudo apt update
          sudo apt install microsoft-edge-beta

      - name: Install Chrome Beta
        if: ${{ startsWith(matrix.browser, 'chrome') }}
        run: |
          curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome-beta.list
          sudo apt-get update
          sudo apt-get install google-chrome-beta

      - name: Extract Branch Name and Set Test Run Name
        id: set-test-run-name
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          echo "::set-output name=TEST_RUN_NAME::${{ matrix.browser }}-${{ github.workflow }}—$BRANCH_NAME"

      - name: Install root dependencies
        run: npm install

      - name: Install test dependencies
        run: npm install
        working-directory: ./test

      - name: Install Cypress
        run: npm install cypress@latest
        working-directory: ./test

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          quiet: true
          working-directory: ./test
          spec: cypress/e2e/test-spec/quick-test_*
          browser: ${{ matrix.browser }}
        #          record: true
        #          parallel: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          #          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PROJECT_TOKEN: ${{ secrets.DEV_EXAMPLE_7 }}
          TEST_RUN_NAME: ${{ steps.set-test-run-name.outputs.TEST_RUN_NAME }}

