name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm install

      - name: Install test dependencies
        run: npm install
        working-directory: ./test



      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          quiet: true
          working-directory: ./test
          spec: cypress/e2e/test-spec/quick-test_view*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_TOKEN: zEvNOYn2/Bk6MdIzzh+0=_dev


