name: mac-and-windows-check
on: [pull_request]

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1 ]
        os: [windows-latest, macos-latest]
#        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #doesn't work on windows
#      - name: Extract Branch Name and Set Test Run Name
#        id: set-test-run-name
#        run: |
#          BRANCH_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
#          echo "::set-output name=TEST_RUN_NAME::${{ github.workflow }}—$BRANCH_NAME"


      - name: Install root dependencies
        run: npm install

      - name: Install test dependencies
        run: npm install
        working-directory: ./test

      - name: Install Cypress
        run: npm install cypress@latest
        working-directory: ./test

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          quiet: true
          working-directory: ./test
          spec: cypress/e2e/test-spec/quick-test_*
#          record: true
#          parallel: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PROJECT_TOKEN: ${{ secrets.DEV_EXAMPLE_7 }}
          TEST_RUN_NAME: "${{ github.workflow }}—${{ runner.os }}—${{ github.ref }}"


