name: mac-and-windows-check
#on: [push]
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1 ]
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install root dependencies
        run: npm install

      - name: Install test dependencies
        run: npm install
        working-directory: ./test

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          quiet: true
          working-directory: ./test
          spec: cypress/e2e/test-spec/quick-test_*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_TOKEN: ${{ secrets.DEV_EXAMPLE_7 }}
          TEST_RUN_NAME: "${{ github.workflow }}—${{ runner.os }}—${{ github.ref }}"
          SBVT_SCM_BRANCH: ${{ github.head_ref || github.ref_name }}
          SBVT_SCM_COMMIT_ID: ${{ github.sha }}
          DEBUG: TRUE



